name: admin_dashboard
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc:
  firebase_core: ^4.2.1
  dio: ^5.9.0
  firebase_auth: ^6.1.2
  cloud_firestore:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  get_it: ^7.6.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  responsive_framework: ^1.1.0
  fl_chart: ^0.66.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Regular.ttf
          weight: 400
